name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17.5

    - name: Build
      run: |
        cd $GITHUB_WORKSPACE
        go build -o $GITHUB_WORKSPACE/auth_server_${{ env.GOOS }}_${{ env.GOARCH }}

    - name: Release Ready
      run: |
        cd $GITHUB_WORKSPACE
        version=$(cat var.go | grep ApplicationVersion | awk '{print $4}' | awk -F '"' '{print $2}')
        echo "VERSION=$version" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v0.1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ env.VERSION }}
        tag_name: ${{ env.VERSION }}
        draft: false
        prerelease: false
        files: |
          $GITHUB_WORKSPACE/auth_server_*
